#!/bin/bash

############################################################################################
# Copyright (C) 2020, Roman Mayer (https://www.youtube.com/channel/UCh8VSOq6cF459y5Yp_4yJbA)
# refined by: Raphipod, 2021
############################################################################################

# Note: Edit in the right file paths for the prefix, for proton, the game path, and change the steamusername to yours.

export SteamGameId=227300
export LD_PRELOAD=:/home/testuser/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so

prefix="/home/testuser/.local/share/Steam/steamapps/compatdata/227300/"
proton="/home/testuser/.local/share/Steam/steamapps/common/Proton*4.11"
game="/home/testuser/.local/share/Steam/steamapps/common/Euro*Truck*Simulator*2"
mod=~/.truckersmp
steamusername=testuser

./truckersmp-cli -e -p -d -s --activate-native-d3dcompiler-47 -g $game  -m $mod -n $steamusername -o $proton -x $prefix