#!/bin/bash

# This script installs Proton-GE for better performance

wget https://github.com/GloriousEggroll/proton-ge-custom/releases/download/6.1-GE-2/Proton-6.1-GE-2.tar.gz

tar -zxvf Proton-6.1-GE-2.tar.gz

# Create new directory for Steam to recognize Proton

sudo mkdir /home/$USER/.steam/root/compatibilitytools.d

# Move Proton folder to compatibilitytools.d for Steam to recognize it.

sudo mv Proton-6.1-GE-2 /home/$USER/.steam/root/compatibilitytools.d